"use client";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { ReduxProvider } from "@/redux/provider";
import { appWithTranslation } from "next-i18next";
import { ReactNode } from "react";
import { AppProps } from "next/app";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

interface RootLayoutProps extends AppProps {
  children: ReactNode;
}

const RootLayout: React.FunctionComponent<RootLayoutProps> = ({ children }) => {
  return (
    <html lang="eng">
      <body className={inter?.className}>
        <ReduxProvider>
          <div className="bg-[url('../../public/skyNight.png')] w-full h-full">
            {children}
          </div>
          <ToastContainer />
        </ReduxProvider>
      </body>
    </html>
  );
};
